import {
  Complaint,
  MaintenanceRequest,
  Visitor,
  Attendance,
  LeaveRequest,
  Announcement,
  Notification,
  InventoryItem,
  AuditLog
} from '../../../src/types/index.ts';

export const seedComplaints: Complaint[] = [
  {
    id: 'comp-1',
    studentId: 's-1',
    studentName: 'Rohan Verma',
    hostelId: 'h-cvr-1',
    hostelName: 'C.V. Raman Boys Hostel',
    roomId: 'r-cvr-101',
    roomNumber: 'A-101',
    category: 'electrical',
    title: 'Ceiling fan making squeaking noise & oscillating erratically',
    description: 'The second ceiling fan in Room A-101 is vibrating heavily and making loud metallic friction noises.',
    priority: 'high',
    status: 'assigned',
    assignedTo: 'u-staff-1',
    assignedStaffName: 'Marcus Vance',
    createdAt: '2025-02-20T08:30:00Z',
    updatedAt: '2025-02-20T09:15:00Z',
  },
  {
    id: 'comp-2',
    studentId: 's-2',
    studentName: 'Ananya Iyer',
    hostelId: 'h-sng-2',
    hostelName: 'Sarojini Naidu Girls Hostel',
    roomId: 'r-sng-101',
    roomNumber: 'G-101',
    category: 'internet',
    title: 'Wi-Fi Access Point on 1st Floor dropping connectivity',
    description: 'Wi-Fi SSIDs keep disappearing every 15 minutes during evening study hours.',
    priority: 'medium',
    status: 'in_progress',
    assignedTo: 'u-staff-1',
    assignedStaffName: 'Marcus Vance',
    createdAt: '2025-02-21T19:00:00Z',
    updatedAt: '2025-02-22T10:00:00Z',
  },
  {
    id: 'comp-3',
    studentId: 's-4',
    studentName: 'Priya Sen',
    hostelId: 'h-sng-2',
    hostelName: 'Sarojini Naidu Girls Hostel',
    roomId: 'r-sng-101',
    roomNumber: 'G-101',
    category: 'plumbing',
    title: 'Water tap leaking continuously in washroom 3',
    description: 'The tap in washroom 3 has a loose spindle causing steady water wastage.',
    priority: 'high',
    status: 'resolved',
    assignedTo: 'u-staff-1',
    assignedStaffName: 'Marcus Vance',
    resolutionNotes: 'Replaced rubber washer and tightened spindle thread.',
    createdAt: '2025-02-18T11:00:00Z',
    updatedAt: '2025-02-19T14:20:00Z',
  },
  {
    id: 'comp-4',
    studentId: 's-3',
    studentName: 'Aditya Kulkarni',
    hostelId: 'h-cvr-1',
    hostelName: 'C.V. Raman Boys Hostel',
    roomId: 'r-cvr-101',
    roomNumber: 'A-101',
    category: 'food',
    title: 'Dinner rotis were undercooked yesterday',
    description: 'The chapatis served at 8:30 PM dinner were chewy and undercooked on one side.',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-02-25T21:30:00Z',
    updatedAt: '2025-02-25T21:30:00Z',
  }
];

export const seedMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'maint-1',
    studentId: 's-1',
    studentName: 'Rohan Verma',
    hostelId: 'h-cvr-1',
    roomId: 'r-cvr-101',
    roomNumber: 'A-101',
    category: 'Electrical Inspection',
    description: 'Annual switchboard inspection and fan bearing lubrication',
    priority: 'high',
    assignedStaff: 'u-staff-1',
    assignedStaffName: 'Marcus Vance',
    status: 'in_progress',
    createdAt: '2025-02-20T09:15:00Z',
  },
  {
    id: 'maint-2',
    hostelId: 'h-sng-2',
    roomId: 'r-sng-101',
    roomNumber: 'G-101',
    category: 'Plumbing Repair',
    description: 'Fix bathroom tap spindle',
    priority: 'medium',
    assignedStaff: 'u-staff-1',
    assignedStaffName: 'Marcus Vance',
    status: 'completed',
    createdAt: '2025-02-18T12:00:00Z',
    completedAt: '2025-02-19T14:20:00Z',
  }
];

export const seedLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    studentId: 's-1',
    studentName: 'Rohan Verma',
    hostelId: 'h-cvr-1',
    roomNumber: 'A-101',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    reason: 'Attending sibling wedding ceremony in hometown.',
    destination: 'Sector 14, Pune',
    emergencyContact: '+1 (555) 888-0011 (Father)',
    status: 'approved',
    approvedBy: 'u-warden-1',
    approverName: 'Prof. Rajesh Sharma',
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'leave-2',
    studentId: 's-3',
    studentName: 'Aditya Kulkarni',
    hostelId: 'h-cvr-1',
    roomNumber: 'A-101',
    startDate: '2026-08-28',
    endDate: '2026-08-29',
    reason: 'Family weekend visit and medical checkup.',
    destination: 'Thane, Mumbai',
    emergencyContact: '+1 (555) 888-0033 (Father)',
    status: 'approved',
    approvedBy: 'u-warden-1',
    approverName: 'Prof. Rajesh Sharma',
    createdAt: '2026-08-26T14:20:00Z',
  },
  {
    id: 'leave-3',
    studentId: 's-2',
    studentName: 'Ananya Iyer',
    hostelId: 'h-sng-2',
    roomNumber: 'G-101',
    startDate: '2026-08-29',
    endDate: '2026-08-31',
    reason: 'Participating in State Level Robotics Hackathon.',
    destination: 'Tech Park, Bangalore',
    emergencyContact: '+1 (555) 888-0022 (Parent)',
    status: 'pending',
    createdAt: '2026-08-27T08:00:00Z',
  }
];

export const seedVisitors: Visitor[] = [
  {
    id: 'vis-1',
    studentId: 's-1',
    studentName: 'Rohan Verma',
    studentRoom: 'A-101',
    visitorName: 'Vikas Verma',
    relationship: 'Father',
    phone: '+1 (555) 888-0011',
    purpose: 'Delivering winter clothes and laptop charger',
    idProofNumber: 'GOV-DL-9827361',
    entryTime: '2026-08-26T14:15:00Z',
    exitTime: '2026-08-26T16:30:00Z',
    status: 'checked_out',
    approvedBy: 'Prof. Rajesh Sharma',
    createdAt: '2026-08-26T14:00:00Z',
  },
  {
    id: 'vis-2',
    studentId: 's-2',
    studentName: 'Ananya Iyer',
    studentRoom: 'G-101',
    visitorName: 'Ramaswamy Iyer',
    relationship: 'Father',
    phone: '+1 (555) 888-0022',
    purpose: 'Meeting student before weekend hackathon travel',
    idProofNumber: 'PASSPORT-Z7829104',
    entryTime: '2026-08-27T10:00:00Z',
    status: 'checked_in',
    approvedBy: 'Dr. Sunita Deshmukh',
    createdAt: '2026-08-27T09:45:00Z',
  }
];

export const seedAttendance: Attendance[] = [
  { id: 'att-1', studentId: 's-1', studentName: 'Rohan Verma', hostelId: 'h-cvr-1', roomNumber: 'A-101', date: '2026-08-27', status: 'present', markedBy: 'Prof. Rajesh Sharma' },
  { id: 'att-2', studentId: 's-2', studentName: 'Ananya Iyer', hostelId: 'h-sng-2', roomNumber: 'G-101', date: '2026-08-27', status: 'present', markedBy: 'Dr. Sunita Deshmukh' },
  { id: 'att-3', studentId: 's-3', studentName: 'Aditya Kulkarni', hostelId: 'h-cvr-1', roomNumber: 'A-101', date: '2026-08-27', status: 'present', markedBy: 'Prof. Rajesh Sharma' },
  { id: 'att-4', studentId: 's-4', studentName: 'Priya Sen', hostelId: 'h-sng-2', roomNumber: 'G-101', date: '2026-08-27', status: 'present', markedBy: 'Dr. Sunita Deshmukh' },
  { id: 'att-5', studentId: 's-5', studentName: 'Kavya Nair', hostelId: 'h-sng-2', roomNumber: 'G-102', date: '2026-08-27', status: 'present', markedBy: 'Dr. Sunita Deshmukh' }
];

export const seedAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Hostel Night & Cultural Dinner Registration Open',
    content: 'All residents are invited to participate in the Annual Hostel Cultural Evening on September 5th. Special feast planned by mess committee.',
    targetRole: 'all',
    priority: 'normal',
    createdBy: 'u-warden-1',
    createdByName: 'Prof. Rajesh Sharma',
    createdAt: '2026-08-24T10:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'Routine Water Tank Cleaning & Disinfection Notice',
    content: 'Overhead water tank sanitization for C.V. Raman Hostel on Saturday 8:00 AM - 12:00 PM. Please store required drinking water in advance.',
    targetRole: 'student',
    hostelId: 'h-cvr-1',
    priority: 'important',
    createdBy: 'u-warden-1',
    createdByName: 'Prof. Rajesh Sharma',
    createdAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'ann-3',
    title: 'Campus Food Wastage Reduction Campaign: Meal Opt-In Reminder',
    content: 'Students are encouraged to indicate meal attendance on the student dashboard before 9 PM for next day meals. Helps our mess reduce food wastage!',
    targetRole: 'all',
    priority: 'important',
    createdBy: 'u-staff-2',
    createdByName: 'Suresh Patil (Mess Supervisor)',
    createdAt: '2026-08-26T09:00:00Z',
  }
];

export const seedNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'u-stu-1',
    title: 'Leave Request Approved',
    message: 'Your leave application from 2026-08-28 to 2026-08-30 has been approved by Warden Prof. Rajesh Sharma.',
    type: 'leave',
    isRead: false,
    link: '/leave',
    createdAt: '2026-08-25T12:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'u-warden-1',
    title: 'New Room Transfer Request',
    message: 'Student Rohan Verma (A-101) has submitted a room transfer request to A-201.',
    type: 'transfer',
    isRead: false,
    link: '/transfers',
    createdAt: '2026-08-25T10:05:00Z',
  },
  {
    id: 'notif-3',
    userId: 'u-stu-1',
    title: 'Meal Opt-In Open for Tomorrow',
    message: 'Please confirm your breakfast, lunch, and dinner attendance to minimize mess food waste.',
    type: 'food',
    isRead: false,
    link: '/food-waste',
    createdAt: '2026-08-27T08:00:00Z',
  }
];

export const seedInventory: InventoryItem[] = [
  { id: 'inv-1', hostelId: 'h-cvr-1', hostelName: 'C.V. Raman Boys Hostel', itemName: 'Study Desk with Bookshelf', category: 'furniture', quantity: 45, availableQuantity: 12, condition: 'good', location: 'Storage Room 1', lastAudited: '2025-01-15' },
  { id: 'inv-2', hostelId: 'h-cvr-1', hostelName: 'C.V. Raman Boys Hostel', itemName: 'Ergonomic Mesh Chair', category: 'furniture', quantity: 45, availableQuantity: 8, condition: 'good', location: 'Storage Room 1', lastAudited: '2025-01-15' },
  { id: 'inv-3', hostelId: 'h-cvr-1', hostelName: 'C.V. Raman Boys Hostel', itemName: 'High-Speed Wi-Fi AP (Ubiquiti)', category: 'electrical', quantity: 12, availableQuantity: 2, condition: 'good', location: 'Server Rack Floor 2', lastAudited: '2025-01-20' },
  { id: 'inv-4', hostelId: 'h-sng-2', hostelName: 'Sarojini Naidu Girls Hostel', itemName: 'Water Purifier (Commercial RO 50LPH)', category: 'sanitary', quantity: 6, availableQuantity: 1, condition: 'good', location: 'Kitchen & Floor Pantries', lastAudited: '2025-01-10' },
  { id: 'inv-5', hostelId: 'h-cvr-1', hostelName: 'C.V. Raman Boys Hostel', itemName: 'Commercial Rice Steamer (30kg)', category: 'kitchen_equipment', quantity: 2, availableQuantity: 2, condition: 'good', location: 'Mess Kitchen', lastAudited: '2025-01-05' }
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: 'u-admin-1',
    userName: 'Lohith Sagar Reddy',
    userRole: 'admin',
    action: 'USER_LOGIN',
    entity: 'User',
    entityId: 'u-admin-1',
    details: 'Admin logged into campus dashboard',
    ipAddress: '192.168.1.100',
    timestamp: '2026-08-27T08:30:00Z',
  },
  {
    id: 'audit-2',
    userId: 'u-warden-1',
    userName: 'Prof. Rajesh Sharma',
    userRole: 'warden',
    action: 'LEAVE_APPROVE',
    entity: 'LeaveRequest',
    entityId: 'leave-1',
    details: 'Approved leave request for Rohan Verma (2026-08-28 to 2026-08-30)',
    ipAddress: '192.168.1.104',
    timestamp: '2026-08-25T12:00:00Z',
  },
  {
    id: 'audit-3',
    userId: 'u-warden-1',
    userName: 'Prof. Rajesh Sharma',
    userRole: 'warden',
    action: 'ROOM_ALLOCATION',
    entity: 'Allocation',
    entityId: 'alloc-1',
    details: 'Allocated Bed 1 in Room A-101 to Rohan Verma',
    ipAddress: '192.168.1.104',
    timestamp: '2024-08-01T09:00:00Z',
  }
];
