import {
  MealAttendance,
  MealPrediction,
  FoodPreparation,
  FoodCost,
  FoodWasteInsight,
  FoodWasteSettings
} from '../../../src/types/index.ts';

export const seedFoodCosts: FoodCost[] = [
  { id: 'fc-1', foodItem: 'Steamed Rice (Basmati Blend)', costPerUnit: 60, unit: 'kg', effectiveFrom: '2025-01-01' },
  { id: 'fc-2', foodItem: 'Dal Tadka / Sambhar', costPerUnit: 120, unit: 'kg', effectiveFrom: '2025-01-01' },
  { id: 'fc-3', foodItem: 'Mixed Seasonal Vegetable Curry', costPerUnit: 85, unit: 'kg', effectiveFrom: '2025-01-01' },
  { id: 'fc-4', foodItem: 'Fresh Whole Wheat Chapati', costPerUnit: 5, unit: 'pieces', effectiveFrom: '2025-01-01' },
  { id: 'fc-5', foodItem: 'Paneer Butter Masala (Special)', costPerUnit: 220, unit: 'kg', effectiveFrom: '2025-01-01' },
  { id: 'fc-6', foodItem: 'Morning Idli / Vada Sambar', costPerUnit: 45, unit: 'servings', effectiveFrom: '2025-01-01' },
  { id: 'fc-7', foodItem: 'Poha / Upma Breakfast', costPerUnit: 35, unit: 'servings', effectiveFrom: '2025-01-01' }
];

export const seedFoodWasteSettings: FoodWasteSettings = {
  wasteThresholdPercent: 10,
  safetyBufferPercent: 3,
  predictionModel: 'WMA_LEAVE_ADJUSTED',
  mealTimings: {
    breakfast: '07:30 - 09:30 AM',
    lunch: '12:30 - 02:30 PM',
    dinner: '07:30 - 09:30 PM',
  }
};

// Seed student meal attendance opt-ins for today and tomorrow
export const seedMealAttendance: MealAttendance[] = [
  { id: 'ma-1', studentId: 's-1', studentName: 'Rohan Verma', date: '2026-08-27', mealType: 'breakfast', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T20:00:00Z' },
  { id: 'ma-2', studentId: 's-1', studentName: 'Rohan Verma', date: '2026-08-27', mealType: 'lunch', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T20:00:00Z' },
  { id: 'ma-3', studentId: 's-1', studentName: 'Rohan Verma', date: '2026-08-27', mealType: 'dinner', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T20:00:00Z' },
  { id: 'ma-4', studentId: 's-2', studentName: 'Ananya Iyer', date: '2026-08-27', mealType: 'breakfast', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T21:15:00Z' },
  { id: 'ma-5', studentId: 's-2', studentName: 'Ananya Iyer', date: '2026-08-27', mealType: 'lunch', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T21:15:00Z' },
  { id: 'ma-6', studentId: 's-2', studentName: 'Ananya Iyer', date: '2026-08-27', mealType: 'dinner', status: 'not_eating', source: 'student_opt_in', createdAt: '2026-08-26T21:15:00Z' },
  { id: 'ma-7', studentId: 's-3', studentName: 'Aditya Kulkarni', date: '2026-08-27', mealType: 'lunch', status: 'eating', source: 'student_opt_in', createdAt: '2026-08-26T19:30:00Z' }
];

// Seed predictions for today (2026-08-27) and tomorrow (2026-08-28)
export const seedMealPredictions: MealPrediction[] = [
  {
    id: 'pred-today-b',
    date: '2026-08-27',
    mealType: 'breakfast',
    totalStudents: 44,
    onLeaveStudents: 0,
    studentOptInEating: 36,
    studentOptInNotEating: 4,
    predictedAttendance: 39,
    recommendedQuantity: 41,
    confidence: 94,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 4.8,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-26T22:00:00Z',
  },
  {
    id: 'pred-today-l',
    date: '2026-08-27',
    mealType: 'lunch',
    totalStudents: 44,
    onLeaveStudents: 0,
    studentOptInEating: 38,
    studentOptInNotEating: 2,
    predictedAttendance: 41,
    recommendedQuantity: 43,
    confidence: 96,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 4.6,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-26T22:00:00Z',
  },
  {
    id: 'pred-today-d',
    date: '2026-08-27',
    mealType: 'dinner',
    totalStudents: 44,
    onLeaveStudents: 0,
    studentOptInEating: 35,
    studentOptInNotEating: 5,
    predictedAttendance: 37,
    recommendedQuantity: 39,
    confidence: 91,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 5.1,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-26T22:00:00Z',
  },
  {
    id: 'pred-tomorrow-b',
    date: '2026-08-28',
    mealType: 'breakfast',
    totalStudents: 44,
    onLeaveStudents: 2, // Rohan & Aditya on approved leave!
    studentOptInEating: 32,
    studentOptInNotEating: 4,
    predictedAttendance: 36,
    recommendedQuantity: 38,
    confidence: 93,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 5.2,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-27T10:00:00Z',
  },
  {
    id: 'pred-tomorrow-l',
    date: '2026-08-28',
    mealType: 'lunch',
    totalStudents: 44,
    onLeaveStudents: 2,
    studentOptInEating: 34,
    studentOptInNotEating: 3,
    predictedAttendance: 38,
    recommendedQuantity: 40,
    confidence: 95,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 5.0,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-27T10:00:00Z',
  },
  {
    id: 'pred-tomorrow-d',
    date: '2026-08-28',
    mealType: 'dinner',
    totalStudents: 44,
    onLeaveStudents: 2,
    studentOptInEating: 31,
    studentOptInNotEating: 6,
    predictedAttendance: 34,
    recommendedQuantity: 36,
    confidence: 89,
    safetyBufferPercent: 3,
    expectedWastage: 2,
    expectedWastagePercent: 5.5,
    modelVersion: 'WMA-v2.4-LeaveAware',
    createdAt: '2026-08-27T10:00:00Z',
  }
];

// Historical food preparation and wastage logs
export const seedFoodPreparations: FoodPreparation[] = [
  // 2026-08-26 (Yesterday)
  {
    id: 'fp-1',
    date: '2026-08-26',
    mealType: 'breakfast',
    foodItem: 'Poha / Upma Breakfast',
    quantityPrepared: 42,
    quantityServed: 40,
    quantityConsumed: 39,
    quantityWasted: 3,
    wastePercentage: 7.14,
    unit: 'servings',
    studentsAttended: 39,
    costPerUnit: 35,
    totalCostWasted: 105,
    reasonForWastage: 'Normal plate-edge surplus',
    createdAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'fp-2',
    date: '2026-08-26',
    mealType: 'lunch',
    foodItem: 'Steamed Rice (Basmati Blend)',
    quantityPrepared: 18, // kg
    quantityServed: 17,
    quantityConsumed: 16.5,
    quantityWasted: 1.5,
    wastePercentage: 8.33,
    unit: 'kg',
    studentsAttended: 42,
    costPerUnit: 60,
    totalCostWasted: 90,
    reasonForWastage: 'Surplus pot remaining after serving window closed',
    createdAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'fp-3',
    date: '2026-08-26',
    mealType: 'lunch',
    foodItem: 'Dal Tadka / Sambhar',
    quantityPrepared: 14,
    quantityServed: 13.2,
    quantityConsumed: 12.8,
    quantityWasted: 1.2,
    wastePercentage: 8.57,
    unit: 'kg',
    studentsAttended: 42,
    costPerUnit: 120,
    totalCostWasted: 144,
    createdAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'fp-4',
    date: '2026-08-26',
    mealType: 'lunch',
    foodItem: 'Mixed Seasonal Vegetable Curry',
    quantityPrepared: 12,
    quantityServed: 11.5,
    quantityConsumed: 11.0,
    quantityWasted: 1.0,
    wastePercentage: 8.33,
    unit: 'kg',
    studentsAttended: 42,
    costPerUnit: 85,
    totalCostWasted: 85,
    createdAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'fp-5',
    date: '2026-08-26',
    mealType: 'lunch',
    foodItem: 'Fresh Whole Wheat Chapati',
    quantityPrepared: 130,
    quantityServed: 124,
    quantityConsumed: 120,
    quantityWasted: 10,
    wastePercentage: 7.69,
    unit: 'pieces',
    studentsAttended: 42,
    costPerUnit: 5,
    totalCostWasted: 50,
    createdAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'fp-6',
    date: '2026-08-26',
    mealType: 'dinner',
    foodItem: 'Steamed Rice (Basmati Blend)',
    quantityPrepared: 16,
    quantityServed: 14.5,
    quantityConsumed: 14.0,
    quantityWasted: 2.0,
    wastePercentage: 12.5,
    unit: 'kg',
    studentsAttended: 36,
    costPerUnit: 60,
    totalCostWasted: 120,
    reasonForWastage: 'Fewer students attended dinner due to late departmental lab submissions',
    createdAt: '2026-08-26T22:00:00Z',
  },
  // 2026-08-25
  {
    id: 'fp-7',
    date: '2026-08-25',
    mealType: 'lunch',
    foodItem: 'Steamed Rice (Basmati Blend)',
    quantityPrepared: 18,
    quantityServed: 17.2,
    quantityConsumed: 17.0,
    quantityWasted: 1.0,
    wastePercentage: 5.56,
    unit: 'kg',
    studentsAttended: 43,
    costPerUnit: 60,
    totalCostWasted: 60,
    createdAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'fp-8',
    date: '2026-08-25',
    mealType: 'dinner',
    foodItem: 'Paneer Butter Masala (Special)',
    quantityPrepared: 15,
    quantityServed: 14.2,
    quantityConsumed: 14.0,
    quantityWasted: 1.0,
    wastePercentage: 6.67,
    unit: 'kg',
    studentsAttended: 40,
    costPerUnit: 220,
    totalCostWasted: 220,
    createdAt: '2026-08-25T22:00:00Z',
  }
];

export const seedFoodWasteInsights: FoodWasteInsight[] = [
  {
    id: 'fwi-1',
    date: '2026-08-27',
    mealType: 'lunch',
    insight: '2 students have approved leaves tomorrow (2026-08-28). Prediction engine automatically lowered recommended lunch headcount from 43 to 40 servings.',
    severity: 'info',
    estimatedWaste: '2 servings (5.0%)',
    estimatedCost: 140,
    recommendation: 'Prepare 16kg Rice and 110 Chapatis instead of baseline 18kg Rice to save approximately ₹280 and avoid over-preparation.',
    createdAt: '2026-08-27T08:00:00Z',
  },
  {
    id: 'fwi-2',
    date: '2026-08-26',
    mealType: 'dinner',
    insight: 'Wednesday dinner attendance has averaged 12% lower than Monday/Tuesday over the last 3 weeks.',
    severity: 'warning',
    estimatedWaste: '2.0 kg rice + 1.2 kg dal',
    estimatedCost: 264,
    recommendation: 'Reduce Wednesday night preparation buffer from 5% to 2% to eliminate late-night surplus.',
    createdAt: '2026-08-26T22:30:00Z',
  }
];
